source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'AFNetworking', '~> 2.5'
pod 'Toast', '~> 3.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'EaseMobSDKFull', :git => 'https://github.com/easemob/sdk-ios-cocoapods-integration.git'
pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-cocoapods.git'


